import type { SeedLead } from "./types";

/** 12 lead demo per il preset EDILIZIA (Ristrutturazioni Rossi). */
export const leadsEdilizia: SeedLead[] = [
  {
    nome: "Laura Conti",
    email: "laura.conti@gmail.com",
    telefono: "+39 339 1122334",
    messaggio:
      "Buongiorno, devo ristrutturare completamente un trilocale di 95 mq in zona Città Studi a Milano. Budget intorno ai 60.000 €. Vorrei iniziare i lavori a settembre, l'appartamento è già libero. Potete fare un sopralluogo?",
    score: 95,
    categoria: "caldo",
    esigenza: "Ristrutturazione completa trilocale 95 mq a Milano, partenza settembre",
    budget: "60.000 €",
    urgenza: "alta",
    bozza_email:
      "Gentile Sig.ra Conti,\n\nla ringraziamo per averci contattato. La ristrutturazione completa del Suo trilocale in zona Città Studi rientra pienamente nelle nostre competenze: da oltre 20 anni realizziamo interventi di questo tipo con squadre proprie e tempi certi.\n\nIl budget indicato è coerente con un intervento completo di qualità su 95 mq. Saremmo lieti di effettuare un sopralluogo gratuito per presentarle un preventivo dettagliato.\n\nLe proponiamo questi appuntamenti:\n• lunedì ore 10:00\n• martedì ore 15:00\n• mercoledì ore 11:30\n\nIn attesa di un Suo riscontro, porgiamo cordiali saluti.\n\nRistrutturazioni Rossi",
    stato: "appuntamento",
    giorniFa: 6,
    ora: "09:14:00",
  },
  {
    nome: "Marco Ferrari",
    email: "m.ferrari78@libero.it",
    telefono: "+39 348 7654321",
    messaggio:
      "Salve, vorrei rifare il bagno di casa (circa 6 mq) a Sesto San Giovanni. Pensavo di spendere sui 18.000 € compresi sanitari e rivestimenti. Quando potreste venire a vedere?",
    score: 88,
    categoria: "caldo",
    esigenza: "Rifacimento bagno 6 mq a Sesto San Giovanni",
    budget: "18.000 €",
    urgenza: "media",
    bozza_email:
      "Gentile Sig. Ferrari,\n\ngrazie per la Sua richiesta. Il rifacimento completo di un bagno di 6 mq con il budget indicato ci consente di proporLe materiali e sanitari di ottima qualità.\n\nSesto San Giovanni rientra nella nostra zona operativa: possiamo organizzare un sopralluogo già nei prossimi giorni.\n\nLe proponiamo:\n• lunedì ore 10:00\n• martedì ore 15:00\n• mercoledì ore 11:30\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "risposto",
    giorniFa: 6,
    ora: "15:42:00",
  },
  {
    nome: "Giulia Romano",
    email: "giulia.romano@outlook.com",
    telefono: null,
    messaggio:
      "Buonasera, abbiamo appena comprato una villetta a Monza e vorremmo fare il cappotto termico e cambiare gli infissi. Superficie esterna circa 220 mq. Che incentivi ci sono? Budget 45-55mila.",
    score: 90,
    categoria: "caldo",
    esigenza: "Cappotto termico e infissi per villetta 220 mq a Monza, con incentivi",
    budget: "45.000-55.000 €",
    urgenza: "media",
    bozza_email:
      "Gentile Sig.ra Romano,\n\ncongratulazioni per l'acquisto della villetta. Il cappotto termico abbinato alla sostituzione degli infissi è uno degli interventi a più alto ritorno: oltre al comfort, può accedere alle detrazioni fiscali vigenti per la riqualificazione energetica, che illustreremo nel dettaglio in sede di sopralluogo.\n\nLe proponiamo questi appuntamenti:\n• lunedì ore 10:00\n• martedì ore 15:00\n• mercoledì ore 11:30\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "nuovo",
    giorniFa: 5,
    ora: "19:03:00",
  },
  {
    nome: "Antonio Esposito",
    email: "a.esposito@email.it",
    telefono: "+39 320 9988776",
    messaggio:
      "Vorrei un preventivo per ristrutturare la cucina, zona Lambrate. Non ho ancora un budget preciso, dipende dal preventivo. Niente fretta.",
    score: 62,
    categoria: "tiepido",
    esigenza: "Ristrutturazione cucina in zona Lambrate, budget da definire",
    budget: null,
    urgenza: "bassa",
    bozza_email:
      "Gentile Sig. Esposito,\n\nla ringraziamo per il Suo interesse. Per fornirLe un preventivo accurato per la ristrutturazione della cucina ci sarebbe utile sapere la metratura indicativa e se prevede di spostare gli impianti.\n\nSe preferisce, possiamo fissare un sopralluogo gratuito e senza impegno.\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "risposto",
    giorniFa: 5,
    ora: "11:27:00",
  },
  {
    nome: "Federica Galli",
    email: "fede.galli@gmail.com",
    telefono: "+39 333 4455667",
    messaggio:
      "Ciao! Stiamo valutando di ristrutturare casa dei miei a Bergamo, un appartamento anni '70 di 110 mq. Però siamo ancora in fase di idee, volevo capire i costi al mq indicativi.",
    score: 48,
    categoria: "tiepido",
    esigenza: "Ristrutturazione appartamento 110 mq a Bergamo, fase esplorativa",
    budget: null,
    urgenza: "bassa",
    bozza_email:
      "Gentile Sig.ra Galli,\n\ngrazie per averci scritto. Per una ristrutturazione completa di un appartamento anni '70 i costi variano molto in base allo stato degli impianti e alle finiture: saremo lieti di darLe un orientamento più preciso.\n\nLe segnaliamo che Bergamo è al limite della nostra zona operativa (Milano e provincia): in sede di sopralluogo valuteremo insieme la fattibilità.\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "nuovo",
    giorniFa: 4,
    ora: "10:08:00",
  },
  {
    nome: "Davide Moretti",
    email: "davide.moretti@pec.it",
    telefono: "+39 345 1212121",
    messaggio:
      "Buongiorno, gestisco tre appartamenti in affitto in zona Isola. Vorrei rifare i bagni di tutti e tre entro fine anno, budget complessivo circa 50.000 €. Possiamo sentirci?",
    score: 92,
    categoria: "caldo",
    esigenza: "Rifacimento bagni di 3 appartamenti in zona Isola entro fine anno",
    budget: "50.000 €",
    urgenza: "alta",
    bozza_email:
      "Gentile Sig. Moretti,\n\nla ringraziamo per la richiesta. Interventi multipli come il Suo ci consentono di ottimizzare squadre e forniture, con un vantaggio concreto sui costi e sui tempi: entro fine anno è un obiettivo realistico se pianifichiamo ora.\n\nLe proponiamo una chiamata o un sopralluogo:\n• lunedì ore 10:00\n• martedì ore 15:00\n• mercoledì ore 11:30\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "appuntamento",
    giorniFa: 4,
    ora: "16:55:00",
  },
  {
    nome: "Sara Bianchi",
    email: "sara.b91@hotmail.it",
    telefono: null,
    messaggio: "Quanto costa imbiancare una camera da letto?",
    score: 22,
    categoria: "freddo",
    esigenza: "Tinteggiatura di una singola camera da letto",
    budget: null,
    urgenza: "non indicata",
    bozza_email:
      "Gentile Sig.ra Bianchi,\n\ngrazie per averci contattato. La nostra attività è specializzata in ristrutturazioni complete e interventi strutturali; la tinteggiatura di una singola stanza non rientra purtroppo tra i lavori che gestiamo direttamente.\n\nRestiamo a disposizione qualora in futuro volesse valutare un intervento più ampio.\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "risposto",
    giorniFa: 3,
    ora: "08:31:00",
  },
  {
    nome: "Luca Greco",
    email: "luca.greco@azienda.com",
    telefono: "+39 02 5566778",
    messaggio:
      "Buongiorno, cerco un'impresa per ristrutturare un ufficio di 200 mq a Roma EUR. Budget 80.000 €. Tempistiche rapide.",
    score: 35,
    categoria: "freddo",
    esigenza: "Ristrutturazione ufficio 200 mq a Roma — fuori zona operativa",
    budget: "80.000 €",
    urgenza: "alta",
    bozza_email:
      "Gentile Sig. Greco,\n\nla ringraziamo per averci contattato e per la fiducia. Purtroppo la nostra zona operativa copre Milano e provincia: non siamo in grado di garantire la qualità e la presenza di cantiere che ci contraddistinguono su Roma.\n\nLe auguriamo di trovare presto il partner giusto per il Suo progetto.\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "risposto",
    giorniFa: 3,
    ora: "14:12:00",
  },
  {
    nome: "Best Crypto Deals",
    email: "noreply@cryptowinz.biz",
    telefono: null,
    messaggio:
      "GUADAGNA 5000€ A SETTIMANA CON IL TRADING AUTOMATICO!!! Clicca qui: http://crypto-winz.biz/promo — offerta limitata, iscriviti ora!",
    score: 2,
    categoria: "spam",
    esigenza: "Messaggio promozionale non pertinente (spam)",
    budget: null,
    urgenza: "non indicata",
    bozza_email: "",
    stato: "nuovo",
    giorniFa: 2,
    ora: "03:47:00",
  },
  {
    nome: "Elena Rizzo",
    email: "elena.rizzo@gmail.com",
    telefono: "+39 347 8899001",
    messaggio:
      "Buonasera, dovrei sistemare casa ma non so bene da dove iniziare. È un bilocale a Cinisello, vecchiotto. Forse il bagno, forse anche l'impianto elettrico. Mi dite voi?",
    score: 55,
    categoria: "tiepido",
    esigenza: "Riqualificazione bilocale a Cinisello, perimetro da definire (bagno, impianto elettrico)",
    budget: null,
    urgenza: "non indicata",
    bozza_email:
      "Gentile Sig.ra Rizzo,\n\ngrazie per averci scritto. Capita spesso di non sapere da dove iniziare: il modo migliore è un sopralluogo gratuito in cui valutiamo insieme lo stato dell'immobile e definiamo le priorità (impianti prima di tutto, poi finiture).\n\nLe andrebbe bene un appuntamento in settimana?\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "nuovo",
    giorniFa: 2,
    ora: "20:18:00",
  },
  {
    nome: "Paolo & Chiara Villa",
    email: "famiglia.villa@gmail.com",
    telefono: "+39 331 2345678",
    messaggio:
      "Buongiorno, abbiamo ricevuto le chiavi di un quadrilocale a San Donato Milanese da ristrutturare completamente prima di trasferirci. Budget max 70.000 €, vorremmo entrare entro Natale. Sopralluogo possibile questa settimana?",
    score: 97,
    categoria: "caldo",
    esigenza: "Ristrutturazione completa quadrilocale a San Donato, consegna entro Natale",
    budget: "70.000 €",
    urgenza: "alta",
    bozza_email:
      "Gentili Sigg. Villa,\n\ngrazie per averci contattato e congratulazioni per la nuova casa. Una ristrutturazione completa con consegna entro Natale è fattibile pianificando subito: il budget indicato è adeguato per un quadrilocale a San Donato.\n\nPossiamo effettuare il sopralluogo già questa settimana:\n• lunedì ore 10:00\n• martedì ore 15:00\n• mercoledì ore 11:30\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "nuovo",
    giorniFa: 1,
    ora: "09:52:00",
  },
  {
    nome: "Roberto N.",
    email: "rob.thebuilder@yahoo.com",
    telefono: null,
    messaggio: "info per piastrelle bagno, le vendete anche solo materiale? grazie",
    score: 15,
    categoria: "freddo",
    esigenza: "Richiesta di sola fornitura materiale (piastrelle), non un lavoro di ristrutturazione",
    budget: null,
    urgenza: "non indicata",
    bozza_email:
      "Gentile Roberto,\n\ngrazie per averci scritto. Siamo un'impresa di ristrutturazioni e non vendiamo materiale al dettaglio; le piastrelle vengono fornite solo nell'ambito dei nostri cantieri.\n\nPer la sola fornitura Le consigliamo di rivolgersi a uno showroom di rivestimenti.\n\nCordiali saluti,\nRistrutturazioni Rossi",
    stato: "nuovo",
    // Molto presto (UTC) così un lead inviato live in call finisce sempre in cima
    giorniFa: 0,
    ora: "05:45:00",
  },
];
